In [3]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import random


def handle_non_numerical_data(data):
    "Converting all non-numerical data to numerical"
    #Store all of the columns into variable
    columns=data.columns.values
    for column in columns:
        text_digit_vals={}
        def convert_to_int(val):
            return text_digit_vals[val]
        if(data[column].dtype!=np.int64 and data[column].dtype!=np.float64):
            #dtype is used to check the data type of the column
            column_contents=data[column].values.tolist()
            unique_elements=set(column_contents)
            x=0
            for unique in unique_elements:
                if(unique not in text_digit_vals):
                    text_digit_vals[unique]=x
                    x+=1
            data[column]=list(map(convert_to_int,data[column]))
    return data

train_data=pd.read_csv("data/train.csv")
train_data=train_data.drop("Id",1)
#We can't perform mathematical operation on string.That's why we have to handle non numerical data
train_data=handle_non_numerical_data(train_data)
train_data

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,4,65.0,8450,0,0,3,1,0,4,...,0,0,0,0,0,2,2008,1,0,208500
1,20,4,80.0,9600,0,0,3,1,0,2,...,0,0,0,0,0,5,2007,1,0,181500
2,60,4,68.0,11250,0,0,2,1,0,4,...,0,0,0,0,0,9,2008,1,0,223500
3,70,4,60.0,9550,0,0,2,1,0,3,...,0,0,0,0,0,2,2006,1,5,140000
4,60,4,84.0,14260,0,0,2,1,0,2,...,0,0,0,0,0,12,2008,1,0,250000
5,50,4,85.0,14115,0,0,2,1,0,4,...,0,0,4,1,700,10,2009,1,0,143000
6,20,4,75.0,10084,0,0,3,1,0,4,...,0,0,0,0,0,8,2007,1,0,307000
7,60,4,NaN,10382,0,0,2,1,0,3,...,0,0,0,1,350,11,2009,1,0,200000
8,50,2,51.0,6120,0,0,3,1,0,4,...,0,0,0,0,0,4,2008,1,5,129900
9,190,4,50.0,7420,0,0,3,1,0,3,...,0,0,0,0,0,1,2008,1,0,118000
10,20,4,70.0,11200,0,0,3,1,0,4,...,0,0,0,0,0,2,2008,1,0,129500
11,60,4,85.0,11924,0,0,2,1,0,4,...,0,0,0,0,0,7,2006,5,2,345000
12,20,4,NaN,12968,0,0,1,1,0,4,...,0,0,0,0,0,9,2008,1,0,144000
13,20,4,91.0,10652,0,0,2,1,0,4,...,0,0,0,0,0,8,2007,5,2,279500
14,20,4,NaN,10920,0,0,2,1,0,3,...,0,0,2,0,0,5,2008,1,0,157000
15,45,2,51.0,6120,0,0,3,1,0,3,...,0,0,1,0,0,7,2007,1,0,132000
16,20,4,NaN,11241,0,0,2,1,0,1,...,0,0,0,1,700,3,2010,1,0,149000
17,90,4,72.0,10791,0,0,3,1,0,4,...,0,0,0,1,500,10,2006,1,0,90000
18,20,4,66.0,13695,0,0,3,1,0,4,...,0,0,0,0,0,6,2008,1,0,159000
19,20,4,70.0,7560,0,0,3,1,0,4,...,0,0,4,0,0,5,2009,7,5,139000
20,60,4,101.0,14215,0,0,2,1,0,3,...,0,0,0,0,0,11,2006,5,2,325300
21,45,2,57.0,7449,0,2,3,3,0,4,...,0,0,1,0,0,6,2007,1,0,139400
22,20,4,75.0,9742,0,0,3,1,0,4,...,0,0,0,0,0,9,2008,1,0,230000
23,120,2,44.0,4224,0,0,3,1,0,4,...,0,0,0,0,0,6,2007,1,0,129900
24,20,4,NaN,8246,0,0,2,1,0,4,...,0,0,4,0,0,5,2010,1,0,154000
25,20,4,110.0,14230,0,0,3,1,0,3,...,0,0,0,0,0,7,2009,1,0,256300
26,20,4,60.0,7200,0,0,3,1,0,3,...,0,0,0,0,0,5,2010,1,0,134800
27,20,4,98.0,11478,0,0,3,1,0,4,...,0,0,0,0,0,5,2010,1,0,306000
28,20,4,47.0,16321,0,0,2,1,0,1,...,0,0,0,0,0,12,2006,1,0,207500
29,30,2,60.0,6324,0,0,2,1,0,4,...,0,0,0,0,0,5,2008,1,0,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,4,60.0,21930,0,0,0,1,0,4,...,0,0,0,0,0,7,2006,1,0,192140
1431,120,4,NaN,4928,0,0,2,1,0,4,...,0,0,0,0,0,10,2009,1,0,143750
1432,30,4,60.0,10800,0,2,3,1,0,4,...,0,0,0,0,0,8,2007,1,0,64500
1433,60,4,93.0,10261,0,0,2,1,0,4,...,0,0,0,0,0,5,2008,1,0,186500
1434,20,4,80.0,17400,0,0,3,2,0,4,...,0,0,0,0,0,5,2006,1,0,160000
1435,20,4,80.0,8400,0,0,3,1,0,4,...,0,0,1,0,0,7,2008,7,5,174000
1436,20,4,60.0,9000,0,0,3,1,0,2,...,0,0,2,0,0,5,2007,1,0,120500
1437,20,4,96.0,12444,0,0,3,1,0,2,...,0,0,0,0,0,11,2008,5,2,394617
1438,20,2,90.0,7407,0,0,3,1,0,4,...,0,0,4,0,0,4,2010,1,0,149700
1439,60,4,80.0,11584,0,0,3,1,0,4,...,0,0,0,0,0,11,2007,1,0,197000
1440,70,4,79.0,11526,0,0,2,3,0,4,...,0,0,0,0,0,9,2008,1,0,191000
1441,120,2,NaN,4426,0,0,3,1,0,4,...,0,0,0,0,0,5,2008,1,0,149300
1442,60,1,85.0,11003,0,0,3,1,0,4,...,0,0,0,0,0,4,2009,1,0,310000
1443,30,4,NaN,8854,0,0,3,1,0,4,...,0,0,0,0,0,5,2009,1,0,121000
1444,20,4,63.0,8500,0,0,3,1,0,2,...,0,0,0,0,0,11,2007,1,0,179600
1445,85,4,70.0,8400,0,0,3,1,0,4,...,0,0,0,0,0,5,2007,1,0,129000
1446,20,4,NaN,26142,0,0,2,1,0,1,...,0,0,0,0,0,4,2010,1,0,157900
1447,60,4,80.0,10000,0,0,3,1,0,4,...,0,0,0,0,0,12,2007,1,0,240000
1448,50,4,70.0,11767,0,0,3,1,0,4,...,0,0,2,0,0,5,2007,1,0,112000
1449,180,2,21.0,1533,0,0,3,1,0,4,...,0,0,0,0,0,8,2006,1,5,92000
1450,90,4,60.0,9000,0,0,3,1,0,2,...,0,0,0,0,0,9,2009,1,0,136000
1451,20,4,78.0,9262,0,0,3,1,0,4,...,0,0,0,0,0,5,2009,5,2,287090
1452,180,2,35.0,3675,0,0,3,1,0,4,...,0,0,0,0,0,5,2006,1,0,145000
1453,20,4,90.0,17217,0,0,3,1,0,4,...,0,0,0,0,0,7,2006,1,5,84500
1454,20,1,62.0,7500,0,1,3,1,0,4,...,0,0,0,0,0,10,2009,1,0,185000
1455,60,4,62.0,7917,0,0,3,1,0,4,...,0,0,0,0,0,8,2007,1,0,175000
1456,20,4,85.0,13175,0,0,3,1,0,4,...,0,0,4,0,0,2,2010,1,0,210000
1457,70,4,66.0,9042,0,0,3,1,0,4,...,0,0,1,1,2500,5,2010,1,0,266500
1458,20,4,68.0,9717,0,0,3,1,0,4,...,0,0,0,0,0,4,2010,1,0,142125
1459,20,4,75.0,9937,0,0,3,1,0,4,...,0,0,0,0,0,6,2008,1,0,147500